import { ColorRGB } from "../pdf/pdf-content.js";

export const NAMED_COLORS: Record<string, ColorRGB> = {
  black: { r: 0, g: 0, b: 0 },
  white: { r: 1, g: 1, b: 1 },
  red: { r: 1, g: 0, b: 0 },
  green: { r: 0, g: 0.5, b: 0 },
  blue: { r: 0, g: 0, b: 1 },
  gray: { r: 0.5, g: 0.5, b: 0.5 },
  grey: { r: 0.5, g: 0.5, b: 0.5 },
  lightgray: { r: 0.83, g: 0.83, b: 0.83 },
  darkgray: { r: 0.66, g: 0.66, b: 0.66 },
  yellow: { r: 1, g: 1, b: 0 },
  cyan: { r: 0, g: 1, b: 1 },
  magenta: { r: 1, g: 0, b: 1 },
  orange: { r: 1, g: 0.65, b: 0 },
  purple: { r: 0.5, g: 0, b: 0.5 },
  transparent: { r: 1, g: 1, b: 1 },
};

export const DEFAULT_ELEMENT_STYLES: Record<string, Record<string, string>> = {
  html: { display: "block" },
  body: { display: "block", margin: "8pt" },
  h1: {
    "font-size": "24pt",
    "font-weight": "bold",
    "margin-top": "12pt",
    "margin-bottom": "12pt",
    display: "block",
  },
  h2: {
    "font-size": "18pt",
    "font-weight": "bold",
    "margin-top": "10pt",
    "margin-bottom": "10pt",
    display: "block",
  },
  h3: {
    "font-size": "14pt",
    "font-weight": "bold",
    "margin-top": "8pt",
    "margin-bottom": "8pt",
    display: "block",
  },
  h4: {
    "font-size": "12pt",
    "font-weight": "bold",
    "margin-top": "6pt",
    "margin-bottom": "6pt",
    display: "block",
  },
  h5: {
    "font-size": "10pt",
    "font-weight": "bold",
    "margin-top": "4pt",
    "margin-bottom": "4pt",
    display: "block",
  },
  h6: {
    "font-size": "8pt",
    "font-weight": "bold",
    "margin-top": "4pt",
    "margin-bottom": "4pt",
    display: "block",
  },
  p: { "margin-top": "8pt", "margin-bottom": "8pt", display: "block" },
  strong: { "font-weight": "bold", display: "inline" },
  b: { "font-weight": "bold", display: "inline" },
  em: { "font-style": "italic", display: "inline" },
  i: { "font-style": "italic", display: "inline" },
  a: { color: "#0000ee", display: "inline" },
  span: { display: "inline" },
  div: { display: "block" },
  table: { display: "table", "margin-top": "8pt", "margin-bottom": "8pt" },
  thead: { display: "table-header-group" },
  tbody: { display: "table-row-group" },
  tfoot: { display: "table-footer-group" },
  tr: { display: "table-row" },
  th: {
    display: "table-cell",
    "font-weight": "bold",
    padding: "4pt",
    "text-align": "left",
  },
  td: { display: "table-cell", padding: "4pt" },
  ul: {
    display: "block",
    "margin-left": "16pt",
    "margin-top": "8pt",
    "margin-bottom": "8pt",
  },
  ol: {
    display: "block",
    "margin-left": "16pt",
    "margin-top": "8pt",
    "margin-bottom": "8pt",
  },
  li: { display: "block", "margin-bottom": "4pt" },
  hr: {
    display: "block",
    "border-bottom": "1pt solid #ccc",
    "margin-top": "8pt",
    "margin-bottom": "8pt",
  },
  head: { display: "none" },
  style: { display: "none" },
  script: { display: "none" },
  meta: { display: "none" },
  link: { display: "none" },
  title: { display: "none" },
};
